export enum OrderStatus {
	PROCESSING = 'PROCESSING',
	SHIPPED = 'SHIPPED',
	CANCELLED = 'CANCELLED',
	DELAYED = 'DELAYED',
	DELIVERED = 'DELIVERED',
	RETURNED = 'RETURNED',
	REFUNDED = 'REFUNDED',
}
