export enum ShopCategory {
	UNKNOWN = 'UNKNOWN',
	TEXTILES = 'TEXTILES',
	HANDICRAFTS = 'HANDICRAFTS',
	JEWELRY = 'JEWELRY',
	CERAMICS = 'CERAMICS',
	LEATHER = 'LEATHER',
	FOOD_AND_BEVERAGES = 'FOOD_AND_BEVERAGES',
	PAINTINGS_AND_ART = 'PAINTINGS_AND_ART',
	MUSICAL_INSTRUMENTS = 'MUSICAL_INSTRUMENTS',
	BASKETRY = 'BASKETRY',
}
