import { ConflictException, Inject, Injectable } from '@nestjs/common';
import { SellerProfileRepository } from '../../datastore/Seller.repo';
import { SellerProfile } from '../../../domain/entities/SellerProfile';
import { CreateSellerDto } from '../../../infra/controllers/dto/CreateSellerDto';
import { AccountRepository } from '../../datastore/Account.repo';
import { AccountRole } from '../../../domain/enums/AccountRole';
import { AccountStatus } from '../../../domain/enums/AccountStatus';
import { Account } from '../../../domain/entities/Account';
import { SellerProfileMapper } from '../../../infra/services/SellerProfileMapper';

@Injectable()
export class CreateSellerUseCase {
	constructor(
		@Inject(SellerProfileRepository)
		private readonly sellerRepository: SellerProfileRepository,
		@Inject(AccountRepository)
		private readonly accountRepository: AccountRepository,
	) {}

	async handle(sellerDto: CreateSellerDto): Promise<SellerProfile> {
		let accountFound: Account | null = null;
		let accountId: string;

		// Si se proporciona userId (ahora es Account._id), buscar por ese id
		if (sellerDto.userId) {
			accountFound = await this.accountRepository.getAccountById(
				sellerDto.userId,
			);
			if (!accountFound) {
				throw new ConflictException('Usuario no encontrado');
			}
			accountId = accountFound.id;

			// Agregar el rol SELLER si no lo tiene
			if (!accountFound.roles.includes(AccountRole.SELLER)) {
				const updatedRoles = [...accountFound.roles, AccountRole.SELLER];
				await this.accountRepository.updateAccountRoles(
					accountId,
					updatedRoles,
				);
			}
		} else {
			// Si no se proporciona userId, buscar por email o crear nueva cuenta
			if (!sellerDto.email || !sellerDto.password) {
				throw new ConflictException(
					'Email y contraseña son requeridos si no se proporciona userId',
				);
			}

			accountFound = await this.accountRepository.getAccountByEmail(
				sellerDto.email,
			);

			if (accountFound) {
				// Si la cuenta ya existe, agregar el rol SELLER si no lo tiene
				accountId = accountFound.id;

				if (!accountFound.roles.includes(AccountRole.SELLER)) {
					const updatedRoles = [...accountFound.roles, AccountRole.SELLER];
					await this.accountRepository.updateAccountRoles(
						accountId,
						updatedRoles,
					);
				}
			} else {
				// Si no existe, crear una nueva cuenta (id will be generated by MongoDB)
				const accountToSave: Account = {
					id: '',
					name: sellerDto.name,
					email: sellerDto.email,
					password: sellerDto.password,
					status: AccountStatus.PENDING,
					roles: [AccountRole.SELLER],
				};
				const savedAccount =
					await this.accountRepository.saveAccount(accountToSave);
				accountId = savedAccount.id;
			}
		}

		// Use Account._id as userId in SellerProfile (foreign key)
		const sellerToSave = SellerProfileMapper.fromCreateDto(
			accountId,
			sellerDto,
		);
		await this.sellerRepository.saveSeller(sellerToSave);
		return sellerToSave;
	}
}
