import { DetailSourceProductDocument } from '../../persistence/superfood/detailSourceProduct.schema';
import { DetailSourceProduct } from '../../../domain/entities/superfoods/DetailSourceProduct';
import { plainToInstance, instanceToPlain } from 'class-transformer';

export class DetailSourceProductMapper {
	static fromDocument(doc: DetailSourceProductDocument): DetailSourceProduct {
		const plain = doc.toObject();
		const { _id: _docId, __v: _v, ...rest } = plain;

		return plainToInstance(DetailSourceProduct, {
			id: _docId.toString(),
			...rest,
		});
	}

	static toPersistence(
		detailSourceProduct: DetailSourceProduct | Partial<DetailSourceProduct>,
	) {
		const plain = instanceToPlain(detailSourceProduct);
		const { id: _id1, _id: _id2, __v: _v2, ...dataForDB } = plain;

		return dataForDB;
	}

	static fromCreateDto(dto: any): DetailSourceProduct {
		const plain = {
			id: '', // Will be generated by MongoDB
			name: dto.name,
			description: dto.description,
			features: dto.features || [],
			createdAt: new Date(),
			updatedAt: new Date(),
		};

		return plainToInstance(DetailSourceProduct, plain);
	}
}
